version: '3.8'

services:
  auth-service:
    build: ./auth-service
    ports:
      - "8080:8080"
    depends_on:
      - db

  cars-service:
    build: ./cars-service
    ports:
      - "8081:8081"
    depends_on:
      - db

  rent-service:
    build: ./rent-service
    ports:
      - "8082:8082"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: rentaluser
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: car_rental_system
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
